# Project information
site_name: SimpleAF
site_url: https://pellcorp.github.io/Simple-AF-Wiki/
site_author: Chris van Liere
site_description: >-
  Unlock the best of your printer with back-to-basic firmware, customizable for all creality printers. Achieve more results with less creality.

# Repository
repo_name: GitHub
repo_url: https://github.com/pellcorp/Simple-AF-Wiki

# Copyright
copyright: SimpleAF &copy; All rights reserved

# Configuration
theme:
  name: material
  custom_dir: material/overrides
  language: en

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  logo: assets/logo.png

  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - navigation.top
    - navigation.tabs
    - navigation.indexes
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - content.footnote.tooltips
    - content.tabs.link
    - toc.follow

    - content.action.edit
    - content.action.view
    - content.tooltips

# Extra styling CSS/Java
extra_css:
  - stylesheets/extra.css

# Plugins
plugins:
  - blog
  - search:
      lang: en
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - tags

# Hooks
hooks:
  - material/overrides/hooks/shortcodes.py
  - material/overrides/hooks/translations.py

# Additional Configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  generator: false
  social:
    - icon: simple/kofi
      link: https://ko-fi.com/pellcorp49698
    - icon: material/hand-coin
      link: https://gofund.me/2033eedb
    - icon: simple/github
      link: https://github.com/pellcorp
    - icon: simple/discord
      link: https://discord.gg/tGGVn5qjgv
  tags:


# Extensions
markdown_extensions:
  - stepslist
  - abbr
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.blocks.caption
  - toc:
      title: On this page
      permalink: true
      toc_depth: 3
        
  - tables
  - admonition
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tasklist:
      custom_checkbox: true

# Page tree
nav:
  - Home: index.md
  - Getting started:
    - Markdown: markdown.md
    - Setup Example: setup.md
  - Changelog:
      - changelog/index.md
  - Examples:
    - FAQ: FAQ.md
    - Installation:
      - Cartographer: installation/probes/cartographer.md
  - Blog:
    - blog/index.md